<option>Αιτωλοακαρνανίας</option>
<option>Αργολίδας</option>
<option>Αρκαδίας</option>
<option>Άρτας</option>
<option>Αττικής</option>
<option>Αχαΐας</option>
<option>Βοιωτίας</option>
<option>Γρεβενών</option>
<option>Δράμας</option>
<option>Δωδεκανήσου</option>
<option>Έβρου</option>
<option>Ευβοίας</option>
<option>Ευρυτανίας</option>
<option>Ζακύνθου</option>
<option>Ηλείας</option>
<option>Ημαθίας</option>
<option>Ηρακλείου</option>
<option>Θεσπρωτίας</option>
<option>Θεσσαλονίκης</option>
<option>Ιωαννίνων</option>
<option>Καβάλας</option>
<option>Καρδίτσας</option>
<option>Καστοριάς</option>
<option>Κερκύρας</option>
<option>Κεφαλληνίας</option>
<option>Κιλκίς</option>
<option>Κοζάνης</option>
<option>Κορινθίας</option>
<option>Κυκλάδων</option>
<option>Λακωνίας</option>
<option>Λάρισας</option>
<option>Λασιθίου</option>
<option>Λέσβου</option>
<option>Λευκάδας</option>
<option>Μαγνησίας</option>
<option>Μεσσηνίας</option>
<option>Ξάνθης</option>
<option>Πέλλας</option>
<option>Πιερίας</option>
<option>Πρέβεζας</option>
<option>Ρεθύμνης</option>
<option>Ροδόπης</option>
<option>Σάμου</option>
<option>Σερρών</option>
<option>Τρικάλων</option>
<option>Φθιώτιδας</option>
<option>Φλώρινας</option>
<option>Φωκίδας</option>
<option>Χαλκιδικής</option>
<option>Χανίων</option>
<option>Χίου</option>



